### ISSUE TITLE
MAC下的问题

### ISSUE THREAD

**Issue by eveinzz** [code-scan/dzscan#11]
Traceback (most recent call last):
  File "dzscan.py", line 286, in <module>
    base.fetch_version()
  File "dzscan.py", line 62, in fetch_version
    req = requests.get(robots_path, headers=HEADERS)
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 53, in request

**Comment by Gotric** [comment]
同样遇到这个错误

**Comment by Debiancc** [comment]
`pip install requests`
needed

**Comment by paradiseduo** [comment]
> `pip install requests`
> needed

已经安装了，依然报这个错误
